# media pipe finger integer
THUMB_TIP_INT = 4
INDEX_FINGER_TIP_INT = 8
MIDDLE_FINGER_TIP_INT = 12
RING_FINGER_TIP_INT = 16
PINKY_TIP_INT = 20

LANDMARK_CIRCLE_RADIUS_INT = 6

EMPTY_STRING = ""
RIGHT_STRING = "RIGHT"
LEFT_STRING = "LEFT"
RIGHT_THUMB_STRING = RIGHT_STRING + "_THUMB"
RIGHT_INDEX_STRING = RIGHT_STRING + "_INDEX"
RIGHT_MIDDLE_STRING = RIGHT_STRING + "_MIDDLE"
RIGHT_RING_STRING = RIGHT_STRING + "_RING"
RIGHT_PINKY_STRING = RIGHT_STRING + "_PINKY"

LEFT_THUMB_STRING = LEFT_STRING + "_THUMB"
LEFT_INDEX_STRING = LEFT_STRING + "_INDEX"
LEFT_MIDDLE_STRING = LEFT_STRING + "_MIDDLE"
LEFT_RING_STRING = LEFT_STRING + "_RING"
LEFT_PINKY_STRING = LEFT_STRING + "_PINKY"

SPIDERMAN_SIGN = "SPIDERMAN"
OPEN_PALM = "OPEN_PALM"
V_SIGN = "V_SIGN"
FIST = "FIST"


RIGHT_POINTER = "RIGHT_POINTER"
RIGHT_SPIDERMAN_SIGN = RIGHT_STRING + "_" + SPIDERMAN_SIGN

LEFT_SPIDERMAN_SIGN = LEFT_STRING + "_" + SPIDERMAN_SIGN
LEFT_OPEN_PALM = LEFT_STRING + "_" + OPEN_PALM
LEFT_V_SIGN = LEFT_STRING + "_" + V_SIGN
LEFT_FIST = LEFT_STRING + "_" + FIST


BOTH_OPEN_PALMS = "BOTH_OPEN_PALMS"


NUM_OF_FRAMES = 13


# Colors
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
PINK = (255, 0, 225)
RED = (0, 0, 225)

CV2_FONT_SIZE = 0.7

# Debug Stuff
LOG_INFO = 20
LOG_WARNING = 30
LOG_ERROR = 40
LOG_RED_LETTERS_START = "\033[31m"
LOG_GREEN_LETTERS_START = "\033[32m"
LOG_YELLOW_LETTERS_START = "\033[33m"
LOG_LETTERS_END = "\033[0m"


CAMERA_ERROR_MESSAGE = "Please check your camera connection and try again."
